# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aihuman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e8f6697d8e3a4445b38a46c948f271ff }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5c4448f866a444d7b60f5c840b196956 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e8f6697d8e3a4445b38a46c948f271ff }}/ninjaasmoke/dma:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aihuman'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1bbf86214fe5466189a852cf32826fd3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e8f6697d8e3a4445b38a46c948f271ff }}/ninjaasmoke/dma:${{ github.sha }}'